### PR TITLE
[MM-40214] Implement App Bar component

### PR DESCRIPTION
**Pull request by mickmister**
#### Summary

This PR makes it so the plugin registers its own component to the App Bar. The core webapp makes it so the component is only mounted if the `AppBarEnabled` feature flag is on. This logic is only in the core webapp, and not in the plugin's source.

The plugin simultaneously registers its usual channel header component, and App Bar component. This is so the webapp can show one or the other when the App Bar feature flag is enabled or disabled. The plugin then doesn't need to watch this feature flag, and the webapp can manage the effects of the flag.

#### Ticket Link

Fixes https://mattermost.atlassian.net/browse/MM-40214

### CODE REVIEW

**Comment by dipak-demansol** [comment]
@mickmister when the app-bar is enable then Note plugin have issue, by click on the note icon i can't see any message or button to add data, i got the blank page, if the app-bar is disable then the same build is working properly, pls see the video

https://user-images.githubusercontent.com/89907719/168976412-2703761d-90b4-495b-a258-41d31fe52bc5.mov

**Comment by agarciamontoro** [comment]
Oh, and it is definitely related to the App Bar icon! Actually, to the channel header icon not being mounted, which is a consequence of rendering the App Bar icon. The problem was that the channel header button component contains logic needed for the correct functioning of the plugin.

**Comment by agarciamontoro** [comment]
The CI failures here are permissions-related, and we cannot fix them until Christopher's back, two weeks from now. I have access to the repo, but not to CircleCI, and it seems we need to create a new deploy key as per https://support.circleci.com/hc/en-us/articles/360021666393-How-to-stop-building-by-manually-removing-the-CircleCI-webhook-and-deploy-key-from-your-GitHub-repository, which I don't have permissions for.

As we need this before the release of v7.0 on June 15 (next Wednesday), we'll merge after @DHaussermann tests it works as expected.

**Comment by DHaussermann** [comment]
As per @agarciamontoro CI failures here are permission related and can't be immediately resolved.

Please merge.

**Pull request merged**
